name: "Deploy ECS"
on:
  workflow_call:
    inputs:
      sha:
        description: 'The git sha to build'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'